<div class="bs-docs-section">
    <div class="well">
        <?php $form->setAttribute('action',$this->url('admin/category',array('action' => 'add'))); ?>
        <?php $form->prepare(); ?>
        <?php echo $this->form()->openTag($form); ?>
        <fieldset>
            <legend>Добавление категории</legend>
            <?php foreach ($form as $element){ ?>
                <div class="form-group">
                    <?php $attributes = $element->getAttributes(); ?>

                    <?php if ($element->getLabel()){ ?>
                        <?php $element->setLabelAttributes(array('class' => 'col-lg-2 control-label'));?>
                        <?php if (isset($attributes['required'])){ ?>
                            <?php $element->setLabel($element->getLabel().' *');  ?>
                        <?php } ?>
                    <?php } ?>

                    <?php if (isset($attributes['type']) && $attributes['type'] == 'text'){ ?>
                        <?php echo $this->formLabel($element);?>
                        <div class="col-lg-10">
                            <?php echo $this->formInput($element);  ?>
                        </div>
                    <?php } elseif (isset($attributes['type']) && $attributes['type'] == 'textarea'){ ?>
                        <?php echo $this->formLabel($element);?>
                        <div class="col-lg-10">
                            <?php echo $this->formTextArea($element);  ?>
                        </div>
                    <?php } elseif (isset($attributes['type']) && $attributes['type'] == 'file'){ ?>
                        <?php echo $this->formLabel($element);?>
                        <div class="col-lg-10">
                            <?php echo $this->formFile($element);  ?>
                        </div>
                    <?php } else { ?>
                        <div class="col-lg-10">
                            <?php echo $this->formRow($element);  ?>
                        </div>
                    <?php } ?>

                </div>
            <?php } ?>
        </fieldset>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>