<?php $this->headLink()
    ->prependStylesheet($this->basePath('css/datatables/dataTables.bootstrap.css'))
;?>

<?php echo $this->headScript()
    ->prependFile($this->basePath('js/fastclick/fastclick.js'))
    ->prependFile($this->basePath('js/slimScroll/jquery.slimscroll.js'))
    ->prependFile($this->basePath('js/dist/js/app.min.js'))
    ->prependFile($this->basePath('js/parser.gis.js'))
    ->prependFile($this->basePath('js/jquery.min.js'))
    ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
; ?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Парсер
        <small>2gis</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Контакты</a></li>
        <li><a href="#">Парсер</a></li>
        <li class="active">2Gis</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="callout callout-info">
        <h4>Предупреждение!</h4>
        <p>Вы работаете с базой которая последний раз обновлялась 21.06.1996 </p>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Фильтор рубрик</h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="">
                        <form action="#" method="post">
                            <div class="col-md-4 form-group">
                                <input class="form-control general_rubric" type="text" data-provide="typeahead" data-id="0">
                            </div>
                            <div class="col-md-7 form-group">
                                <input class="form-control sub_rubric" type="text" data-provide="typeahead" data-id="0">
                            </div>
                            <div class="col-md-1 form-group">
                                <button class="form-control" type="submit"><i class="fa fa-refresh" aria-hidden="true"></i></button>
                            </div>
                        </form>
                    </div>
                    <!-- /.table-responsive -->
                </div>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Настройки</h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="table-responsive">
                        <label class="label label-info">Выводить</label>
                        <ul class="ui-sortable">
                            <li>
                                <input type="checkbox" checked value="">
                                <span class="text">Проверенные</span>
                            </li>
                            <li>
                                <input type="checkbox" value="" checked>
                                <span class="text">Проблемные</span>
                            </li>
                            <li>
                                <input type="checkbox" value="" checked>
                                <span class="text">Без статуса</span>
                            </li>
                        </ul>
                    </div>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.box-body -->
                <div class="box-footer clearfix">
                    <a href="javascript:void(0)" class="btn btn-sm btn-primary btn-flat pull-right">Приминить фильтр данных</a>
                </div>
                <!-- /.box-footer -->
            </div>
        </div>
        <div class="col-md-9">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Data Table With Full Features</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="dataTables_length" id="example1_length">
                                    <label>Show
                                        <select name="example1_length" aria-controls="example1" class="form-control input-sm">
                                            <option value="10">10</option>
                                            <option value="25">25</option>
                                            <option value="50">50</option>
                                            <option value="100">100</option>
                                        </select> entries
                                    </label>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div id="example1_filter" class="dataTables_filter">
                                    <label>Search:
                                        <input type="search" class="form-control input-sm" placeholder="" aria-controls="example1">
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1">Rendering engine</th>
                                            <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1">Browser</th>
                                            <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1">Platform(s)</th>
                                            <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1">Engine version</th>
                                            <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1">CSS grade</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr role="row" class="odd">
                                            <td class="">Other browsers</td>
                                            <td class="">All others</td>
                                            <td class="sorting_1">-</td>
                                            <td class="">-</td>
                                            <td>U</td>
                                        </tr><tr role="row" class="even">
                                            <td class="">Misc</td>
                                            <td class="">NetFront 3.4</td>
                                            <td class="sorting_1">Embedded devices</td>
                                            <td class="">-</td>
                                            <td>A</td>
                                        </tr><tr role="row" class="odd">
                                            <td class="">Misc</td>
                                            <td class="">NetFront 3.1</td>
                                            <td class="sorting_1">Embedded devices</td>
                                            <td class="">-</td>
                                            <td>C</td>
                                        </tr><tr role="row" class="even">
                                            <td class="">Misc</td>
                                            <td class="">Dillo 0.8</td>
                                            <td class="sorting_1">Embedded devices</td>
                                            <td class="">-</td>
                                            <td>X</td>
                                        </tr><tr role="row" class="odd">
                                            <td class="">Gecko</td>
                                            <td class="">Epiphany 2.20</td>
                                            <td class="sorting_1">Gnome</td>
                                            <td class="">1.8</td>
                                            <td>A</td>
                                        </tr><tr role="row" class="even">
                                            <td class="">Webkit</td>
                                            <td class="">iPod Touch / iPhone</td>
                                            <td class="sorting_1">iPod</td>
                                            <td class="">420.1</td>
                                            <td>A</td>
                                        </tr><tr role="row" class="odd">
                                            <td class="">KHTML</td>
                                            <td class="">Konqureror 3.1</td>
                                            <td class="sorting_1">KDE 3.1</td>
                                            <td class="">3.1</td>
                                            <td>C</td>
                                        </tr><tr role="row" class="even">
                                            <td class="">KHTML</td>
                                            <td class="">Konqureror 3.3</td>
                                            <td class="sorting_1">KDE 3.3</td>
                                            <td class="">3.3</td>
                                            <td>A</td>
                                        </tr><tr role="row" class="odd">
                                            <td class="">KHTML</td>
                                            <td class="">Konqureror 3.5</td>
                                            <td class="sorting_1">KDE 3.5</td>
                                            <td class="">3.5</td>
                                            <td>A</td>
                                        </tr><tr role="row" class="even">
                                            <td class="">Tasman</td>
                                            <td class="">Internet Explorer 5.1</td>
                                            <td class="sorting_1">Mac OS 7.6-9</td>
                                            <td class="">1</td>
                                            <td>C</td>
                                        </tr>
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th rowspan="1" colspan="1">Rendering engine</th>
                                            <th rowspan="1" colspan="1">Browser</th>
                                            <th rowspan="1" colspan="1">Platform(s)</th>
                                            <th rowspan="1" colspan="1">Engine version</th>
                                            <th rowspan="1" colspan="1">CSS grade</th></tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-5">
                                <div class="dataTables_info" id="example1_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div>
                            </div>
                            <div class="col-sm-7">
                                <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
                                    <ul class="pagination">
                                        <li class="paginate_button previous disabled" id="example1_previous">
                                            <a href="#" aria-controls="example1" data-dt-idx="0" tabindex="0">Previous</a></li>
                                        <li class="paginate_button active">
                                            <a href="#" aria-controls="example1" data-dt-idx="1" tabindex="0">1</a>
                                        </li>
                                        <li class="paginate_button ">
                                            <a href="#" aria-controls="example1" data-dt-idx="2" tabindex="0">2</a>
                                        </li><li class="paginate_button "><a href="#" aria-controls="example1" data-dt-idx="3" tabindex="0">3</a></li>
                                        <li class="paginate_button "><a href="#" aria-controls="example1" data-dt-idx="4" tabindex="0">4</a></li>
                                        <li class="paginate_button "><a href="#" aria-controls="example1" data-dt-idx="5" tabindex="0">5</a></li>
                                        <li class="paginate_button "><a href="#" aria-controls="example1" data-dt-idx="6" tabindex="0">6</a></li>
                                        <li class="paginate_button next" id="example1_next">
                                            <a href="#" aria-controls="example1" data-dt-idx="7" tabindex="0">Next</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>

</section>
<!-- /.content -->